name: Pipeline fiap-car-reg

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - run: |
          set -x
          docker version

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4
      
      - name: oc login
        run: |
          oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker build
        run: |
          docker build -t wienerdev/fiap-car-reg:latest .

      - name: Docker login
        run: |
          docker login -u wienerdev -p ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Docker push
        run: |
          docker push wienerdev/fiap-car-reg:latest

      - name: oc import image
        run: |
         oc import-image image-registry.openshift-image-registry.svc:5000/wienerdev-dev/fiap-car-reg-api-2:latest --from=wienerdev/fiap-car-reg-api-2:latest --confirm

      - name: Deploy App
        run: |
          oc patch dc fiap-car-reg -p '{"spec":{"template":{"spec":{"containers":[{"name":"fiap-car-reg","image":"default-route-openshift-image-registry.apps.sandbox-m4.g2pi.p1.openshiftapps.com/wienerdev-dev/fiap-car-reg-api-2"}]}}}}' -n wienerdev-dev
      
      - name: oc rollout 
        run: |
          oc rollout status dc/fiap-car-reg -n wienerdev-dev
